eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8480
spring:
  application:
    name: service1
  # zipkin 地址，这里indows本地直接启动
  zipkin:
      base-url: http://localhost:9511/
  # 抓取频率，1 表示100%抓取 0 表示不抓取
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    root: debug
# ALL	各级包括自定义级别
# DEBUG	指定细粒度信息事件是最有用的应用程序调试
# ERROR	错误事件可能仍然允许应用程序继续运行
# FATAL	指定非常严重的错误事件，这可能导致应用程序中止
# INFO	指定能够突出在粗粒度级别的应用程序运行情况的信息的消息
# OFF	这是最高等级，为了关闭日志记录
# TRACE	指定细粒度比DEBUG更低的信息事件
# WARN	指定具有潜在危害的情况