eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8480
spring:
  application:
    name: service1
  zipkin:
      base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    root: debug