eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8321
spring:
  application:
    name: spring-ribbon-service
#新增配置策略
spring-demo-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
