server:
  port: 8766
spring:
  application:
    name: scheduler-service

regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite-springboot

stockJob:
  # cron  为定时任务的cron表达式；
  cron: 0/5 * * * * ?
  # shardingTotalCount  为任务的分数量（即同时同时开几个定时任务）；
  shardingTotalCount: 2
  # shardingItemParameters  为任务分片携带的参数；
  shardingItemParameters: 0=Chengdu0,1=Chengdu1

