spring:
  application:
    name: spriing-demo-service-feign
server:
  port: 8382

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Ribbon 的负载均衡策略
spring-demo-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    enabled: true

#默认 Actuator 只暴露了2个端点，heath 和 info ,所以如下配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

#实心圆：颜色代表健康度，（绿-黄-红-橙递减）；大小代表并发量。
#曲线：请求量的变化
#

